//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::{
    clicks::Entity as Clicks, links::Entity as Links, o_auth2_sessions::Entity as OAuth2Sessions,
    users::Entity as Users,
};
